services:

  postgres-prod:
    image: postgres:16
    container_name: postgres-prod
    restart: unless-stopped
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin123
      POSTGRES_DB: gestion_commerciale
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ../backups:/backups
    networks:
      - backup_net

  backup-server:
    build:
      context: .
      dockerfile: Dockerfile.backup
    container_name: backup-server
    restart: unless-stopped
    volumes:
      - ../scripts:/scripts
      - ../backups:/backups
      - ../logs:/logs
    networks:
      - backup_net
    depends_on:
      - postgres-prod

  minio:
    image: quay.io/minio/minio
    container_name: minio
    restart: unless-stopped
    command: server /data --console-address ":9001"
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin123
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - minio_data:/data
    networks:
      - backup_net

volumes:
  postgres_data:
  minio_data:

networks:
  backup_net:
    driver: bridge
